name: pheasant_router
description: >-
  The Pheasant Framework Routing Package, for single-page and server-side routing of your pheasant applications.
version: 0.0.1-pr
repository: https://github.com/pheasantframework/router

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  pheasant: ^0.1.0-grade
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
